/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as MemoryVaultRouteImport } from './routes/memory-vault'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryVaultRoute = MemoryVaultRouteImport.update({
  id: '/memory-vault',
  path: '/memory-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/insights': typeof InsightsRoute
  '/memory-vault': typeof MemoryVaultRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/insights': typeof InsightsRoute
  '/memory-vault': typeof MemoryVaultRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/insights': typeof InsightsRoute
  '/memory-vault': typeof MemoryVaultRoute
  '/tests': typeof TestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/exercises'
    | '/insights'
    | '/memory-vault'
    | '/tests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/exercises'
    | '/insights'
    | '/memory-vault'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/exercises'
    | '/insights'
    | '/memory-vault'
    | '/tests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExercisesRoute: typeof ExercisesRoute
  InsightsRoute: typeof InsightsRoute
  MemoryVaultRoute: typeof MemoryVaultRoute
  TestsRoute: typeof TestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-vault': {
      id: '/memory-vault'
      path: '/memory-vault'
      fullPath: '/memory-vault'
      preLoaderRoute: typeof MemoryVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExercisesRoute: ExercisesRoute,
  InsightsRoute: InsightsRoute,
  MemoryVaultRoute: MemoryVaultRoute,
  TestsRoute: TestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
